group:
  # projects with rever releases
  - repos: |
      conda-sandbox/test-synced
    files:
      # rever config
      - source: .github/sync/rever.xsh
        dest: rever.xsh
      # release docs
      - source: .github/sync/RELEASE.md
        dest: RELEASE.md
        template: true
