name: Update

on:
  # every Sunday at 00:00 UTC
  # https://crontab.guru/#0_0_*_*_0
  # schedule:
  #   - cron: '0 0 * * 0'

  # https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_dispatch
  workflow_dispatch:

  issue_comment:
    types:
      - created

jobs:
  update:
    if: >-
      !github.event.repository.fork
      && (
        github.event_name == 'schedule'
        || github.event_name == 'workflow_dispatch'
        || (
          github.event.issue.pull_request
          && github.event.comment.body == '@conda-bot render'
        )
      )
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1

      - if: github.event_name == 'issue_comment' && github.event.comment.body == '@conda-bot render'
        name: configure git origin
        run: |
          echo REPOSITORY=$(curl --silent ${{ github.event.issue.pull_request.url }} | jq --raw-output '.head.repo.full_name') >> $GITHUB_ENV
          echo REF=$(curl --silent ${{ github.event.issue.pull_request.url }} | jq --raw-output '.head.ref') >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          repository: ${{ env.REPOSITORY || github.repository }}
          ref: ${{ env.REF || '' }}

      - name: configure git user
        run: |
          git config user.name 'Conda Bot'
          git config user.email '18747875+conda-bot@users.noreply.github.com'

      - name: combine recent durations from artifacts
        uses: conda/actions/combine-durations@combine-durations

      - name: commit updated durations
        run: git add . && git commit --message "Update test durations" || true

      - name: sync & template files
        uses: conda/actions/template-files@template-files

      - name: commit templated files
        run: git add . && git commit --message "Sync files" || true

      - if: github.event_name != 'issue_comment' || github.event.comment.body == '@conda-bot recreate'
        name: create update PR
        uses: peter-evans/create-pull-request@v5
        with:
          push-to-fork: kenodegard-bot/${{ github.event.repository.name }}
          token: ${{ secrets.SYNC_TOKEN }}
          branch: update
          delete-branch: true
          title: 🤖 Update
          body: |
            [update.yml]: ${{ github.server_url }}/${{ github.repository }}/blob/main/.github/workflows/update.yml

            This is your friendly update PR

            Created automatically by the [`update.yml`][update.yml] workflow, see ${{  }}.

            <details>
            <summary>Commands</summary>

            Trigger actions by commenting on this PR:

            - `@conda-bot render` will run rendering workflows and commit and push any changes to this PR
            - `@conda-bot recreate` will recreate this PR, overwriting any edits that have been made to it

            </details>

      - if: github.event_name == 'issue_comment' && github.event.comment.body == '@conda-bot render'
        id: git-push
        run: git push --force-with-lease

      - if: failed(step.git-push)
        uses: sticky comment